services:
  - type: web
    name: claper-presentation
    env: node
    plan: free
    buildCommand: npm install && npm --prefix client install && npm --prefix server install && npm --prefix client run build
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
